# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_apps', '0002_register_user_level'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
