# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('message_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
